# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='adoutme',
            new_name='aboutme',
        ),
    ]
